"""Animation and temporal processing engine for DrawCV."""

from drawcv.animation.easing import (
    EASING_FUNCTIONS,
    ease_in,
    ease_in_bounce,
    ease_in_circ,
    ease_in_cubic,
    ease_in_elastic,
    ease_in_expo,
    ease_in_out,
    ease_in_out_bounce,
    ease_in_out_circ,
    ease_in_out_cubic,
    ease_in_out_elastic,
    ease_in_out_expo,
    ease_in_out_quad,
    ease_in_out_sine,
    ease_in_quad,
    ease_in_sine,
    ease_out,
    ease_out_bounce,
    ease_out_circ,
    ease_out_cubic,
    ease_out_elastic,
    ease_out_expo,
    ease_out_quad,
    ease_out_sine,
    get_easing,
    linear,
)
from drawcv.animation.interpolation import (
    lerp,
    lerp_bounds,
    lerp_color,
    lerp_point,
    lerp_transform,
    resolve_interpolator,
)
from drawcv.animation.timing import Timing
from drawcv.animation.timeline import Timeline
from drawcv.animation.track import AnimationTrack
from drawcv.animation.video_renderer import VideoRenderer

__all__ = [
    "Timing",
    "Timeline",
    "AnimationTrack",
    "VideoRenderer",
    "linear",
    "ease_in",
    "ease_out",
    "ease_in_out",
    "ease_in_quad",
    "ease_out_quad",
    "ease_in_out_quad",
    "ease_in_cubic",
    "ease_out_cubic",
    "ease_in_out_cubic",
    "ease_in_sine",
    "ease_out_sine",
    "ease_in_out_sine",
    "ease_in_expo",
    "ease_out_expo",
    "ease_in_out_expo",
    "ease_in_circ",
    "ease_out_circ",
    "ease_in_out_circ",
    "ease_in_bounce",
    "ease_out_bounce",
    "ease_in_out_bounce",
    "ease_in_elastic",
    "ease_out_elastic",
    "ease_in_out_elastic",
    "get_easing",
    "EASING_FUNCTIONS",
    "lerp",
    "lerp_point",
    "lerp_color",
    "lerp_transform",
    "lerp_bounds",
    "resolve_interpolator",
]
